server:
  port: 8443

spring:
  application:
    name: mircroservice-consumer-dept-8443

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka