spring:
  application:
    name: microservice-eureka14
server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false